# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

#Books 

Book.create(title: "FirstPerson Singular", description:"“… a blazing and brilliant return to form … a taut and tight, suspenseful and spellbinding, witty and wonderful group of eight stories … there isn’t a weak one in the bunch. The stories echo with Murakami’s preoccupations. Nostalgia and longing for the charged, evocative moments of young adulthood. Memory’s power and fragility; how identity forms from random decisions, ‘minor incidents,’ and chance encounters; the at once intransigent and fragile nature of the ‘self.’ Guilt, shame, and regret for mistakes made and people damaged by foolish or heartless choices. The power and potency of young love and the residual weight of fleeting erotic entanglements. Music’s power to make indelible impressions, elicit buried memories, connect otherwise very different people, and capture what words cannot. The themes become a kind of meter against which all the stories make their particular, chiming rhythms … The reading experience is unsettled by a pervasive blurring of the lines between fantasy and reality, dream and waking … Most of the narrators foreground the act of telling and ruminate on the intention behind and effects of disclosing secrets, putting inchoate impulses, fears, or yearnings into clear, logical prose … This mesmerizing collection would make a superb introduction to Murakami for anyone who hasn’t yet fallen under his spell; his legion of devoted fans will gobble it up and beg for more.”", author_id: 4, subject_id:6 )
Book.create(title: "Milk Blood Heat", description:"“Mortality is the undercurrent in Dantiel W. Moniz’s electrifying debut story collection, Milk Blood Heat, but where there’s death there is the whir of life, too. A lot of collections consist of some duds, yet every single page in this book is a shimmering seashell that contains the sound of multiple oceans. Reading one of Moniz’s stories is like holding your breath underwater while letting the salt sting your fresh wounds. It’s exhilarating and shocking and even healing. The power in these stories rests in their veracity, vitality and vulnerability.”",  author_id: 5, subject_id: 10)
Book.create(title: "The Dangers Of Smoking in Bed", description:"“There’s something thrilling about other people’s suffering—at least within this collection’s 12 stories of death, sex and the occult. Horrors are relayed in a stylish deadpan … Enriquez’s plots deteriorate with satisfying celerity … Largely it’s insatiable women, raggedy slum dwellers and dead children—those who are ordinarily powerless—who wield unholy power in this collection, and they seem uninterested in being reasonable. And Enriquez is particularly adept at capturing the single-minded intensity of teenage girls … If some of these stories end vaguely, the best ones close on the verge of some transgressive climax … To Enriquez, there’s pleasure in the perverse.”",  author_id: 6, subject_id: 3)
Book.create(title: "The Souvenir Museum", description:"“Elizabeth McCracken’s The Souvenir Museum begins with one of the funniest short stories I’ve read in a long time … I had to stop reading ‘The Irish Wedding’ several times to explain to my husband why I was laughing so hard. I kept thinking: I wish I were reading a whole book about these people … they’re all beguiling … This tale, like much of McCracken’s work, captures the mixed bag that characterizes most people’s lives … McCracken’s writing is never dull. She ends this fantastic collection with a second English wedding and its aftermath, nearly 20 years after the first, delivering happiness tempered by sobering circumstances—and a satisfying symmetry.”",  author_id: 7, subject_id:6 )
Book.create(title: "Wild Swims", description:"“How slippery the work of the Danish writer Dorthe Nors is, how it sideswipes and gleams … The stories are vivid the way a flash of immobilizing pain is vivid … Perhaps because they’re so very short and because they mostly sketch slight interior shifts in her characters, Nors’s stories all feel a little bashful, a little tender. Surely this is intentional … Most of her stories are too short to linger deeply in time or consciousness; the characters spin back into their silence almost as soon as they emerge on the page. Nors is a master at portraying female rage, but here there is also no violent explosion outward, instead a sort of inner collapse; her characters assiduously resist confronting their fury until it rises up against them and attacks their bodies … The sense of simultaneous, furious upwelling into text and retraction into shame or reticence gives the stories a powerful undercurrent, as if they were constantly wrestling with themselves. Inherently self-contradicting, they wobble interestingly on their axes, pulled between outraged individualism and the restrictive Janteloven.”",  author_id:8 , subject_id:8 )
Book.create(title: "Walking on Cowrie", description:"“The pure energy of the words strikes first, the thrumming, soaring, frenetic pace of Nana Nkweti’s expression … None of these stories end with a miraculous healing. Even where revelations occur, they never erase scars. Nkweti uses genre tropes to subvert our expectations. She employs the zombie story, the fairy tale, and the confessional in order to invert conventions … The levity of Nkweti’s writing can make even passing descriptions a delight … Occasionally the writing veers into the overwrought … But the sheer speed of Nkweti’s expression allows for correction in midair, and her keen descriptive eye provides more pleasures than missteps … Her inventiveness dazzles.”", author_id: 9, subject_id: 6)
Book.create(title: "My Monticello", description:"“Jocelyn Nicole Johnson uses history to spectacular effect in her debut fiction collection … What makes My Monticelloparticularly resonant is that it does not stray far from life as we know it today. In the near future conjured by Johnson, there are the heat waves and wildfires that bring climate change into view. There is fallout from a fraught election. There is the vile replacement theory rhetoric of the right wing. But the lives of Johnson’s richly drawn characters—their personal stories—are always in focus. And, because of it, the storytelling is propulsive, as we follow these refugees along a harrowing journey, with danger ever at their heels. My Monticello is, quite simply, an extraordinary debut from a gifted writer with an unflinching view of history and what may come of it.”",  author_id: 10, subject_id:10 )
# Book.create(title: "", description:"")
# Book.create(title: "", description:"")

#Author

# Author.create(name:"Pricilla Gilman", age:31)
# Author.create(name:"Kevin Barry", age:29)
# Author.create(name:"Dantiel W.Moniz", age:56)
# Author.create(name:"Mariana Enriquez", age:53)
# Author.create(name:"Elizabeth McCracken", age:47)
# Author.create(name:"Dorthe Nors", age:52)
# Author.create(name:"Nana Nkweti", age:36)
# Author.create(name:"Jocelyn Nicole Johnson", age:48)
# # Author.create(name:"", age:)